# Generated by Django 4.1.13 on 2024-07-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerapp', '0002_leafimage_delete_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='LeafImage',
        ),
    ]
