# Generated by Django 4.1.13 on 2024-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerapp', '0003_imageupload_delete_leafimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='name',
            field=models.TextField(default='leaf image'),
        ),
    ]
