# Generated by Django 4.1.13 on 2024-07-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeafImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_rgb_value', models.JSONField()),
                ('category', models.CharField(max_length=50)),
                ('green_object_image', models.TextField()),
            ],
        ),
    ]
